INSERT INTO Fruit(id,name,season) VALUES ( 1 , 'Mango'      , 'Spring' );
INSERT INTO Fruit(id,name,season) VALUES ( 2 , 'Strawberry' , 'Spring' );
INSERT INTO Fruit(id,name,season) VALUES ( 3 , 'Orange'     , 'Winter' );
INSERT INTO Fruit(id,name,season) VALUES ( 4 , 'GrapeFruit' , 'Winter' );
INSERT INTO Fruit(id,name,season) VALUES ( 5 , 'Blueberry'  , 'Summer' );
INSERT INTO Fruit(id,name,season) VALUES ( 6 , 'Banana'     , 'Summer' );
INSERT INTO Fruit(id,name,season) VALUES ( 7 , 'Plum'       , 'Summer' );
INSERT INTO Fruit(id,name,season) VALUES ( 8 , 'Apple'      , 'Fall'   );
INSERT INTO Fruit(id,name,season) VALUES ( 9 , 'Grape '     , 'Fall'   );
ALTER SEQUENCE fruit_seq RESTART WITH 10;